/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package StudentInformationSystem;

import java.awt.Window;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import StudentInformationSystem.AdminFrame;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author kadir
 */
public class SystemMainPage extends javax.swing.JFrame {

   

    /**
     * Creates new form SystemMainPage
     */
    public SystemMainPage() {
        initComponents();
        NoteEntry.setVisible(false);
        MainPage.setVisible(true);
       
        ListOfStudent.setVisible(false);
        Settings.setVisible(false);
        StudentReg.setVisible(false);
        Database database=new Database();
        database.getStudents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        exitbutt = new javax.swing.JButton();
        ListOfStudents = new javax.swing.JButton();
        studentreg = new javax.swing.JButton();
        note = new javax.swing.JButton();
        settbutt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        MainPage = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ListOfStudent = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StudentReg = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NoteEntry = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitbutt.setText("Exit");
        exitbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttActionPerformed(evt);
            }
        });
        jPanel1.add(exitbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 140, 40));

        ListOfStudents.setText("List Of Students");
        ListOfStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListOfStudentsActionPerformed(evt);
            }
        });
        jPanel1.add(ListOfStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        studentreg.setText("Student Registration");
        studentreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentregActionPerformed(evt);
            }
        });
        jPanel1.add(studentreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 40));

        note.setText("Note Entry ");
        note.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteActionPerformed(evt);
            }
        });
        jPanel1.add(note, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, 40));

        settbutt.setText("Settings");
        settbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settbuttActionPerformed(evt);
            }
        });
        jPanel1.add(settbutt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentInformationSystem/blackBackground.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 380));

        Main.setLayout(new javax.swing.OverlayLayout(Main));

        MainPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentInformationSystem/logo.png"))); // NOI18N
        MainPage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, 210));

        jLabel30.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel30.setText("WELCOME");
        MainPage.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel31.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel31.setText("STUDENT INFORMATION SYSTEM");
        MainPage.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 440, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentInformationSystem/background.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        MainPage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-44, 5, -1, -1));

        Main.add(MainPage);

        ListOfStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        jLabel26.setText("LIST OF STUDENTS");
        ListOfStudent.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("All Class");
        jRadioButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton11MouseClicked(evt);
            }
        });
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });
        ListOfStudent.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 70, 30));

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("11");
        jRadioButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton9MouseClicked(evt);
            }
        });
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });
        ListOfStudent.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 50, 30));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("9");
        jRadioButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton7MouseClicked(evt);
            }
        });
        ListOfStudent.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 30));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("12");
        jRadioButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton8MouseClicked(evt);
            }
        });
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        ListOfStudent.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 60, 30));

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("10");
        jRadioButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton10MouseClicked(evt);
            }
        });
        ListOfStudent.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 60, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "School Number", "Name Surname", "Gender", "Midterm", "Final", "Project"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        ListOfStudent.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 490, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentInformationSystem/background.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        ListOfStudent.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 370));

        Main.add(ListOfStudent);

        Settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("DELETE ALL INFORMATION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Settings.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel18.setText("NEW USER NAME:");
        Settings.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        jLabel19.setText("NEW PASSWORD:");
        Settings.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jLabel20.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel20.setText("WARNING!");
        Settings.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Settings.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));
        Settings.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 160, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        Settings.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));

        jLabel21.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel21.setText("SETTINGS");
        Settings.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 20));
        Settings.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 100, 20));
        Settings.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 220, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentInformationSystem/background.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        Settings.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        Main.add(Settings);

        StudentReg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(jRadioButton1);
        jRadioButton1.setText("Male");
        StudentReg.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        buttonGroup2.add(jRadioButton2);
        jRadioButton2.setText("Female");
        StudentReg.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        StudentReg.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 160, -1));

        jLabel12.setText("Name and Surname:");
        StudentReg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        jLabel14.setText("Gender:");
        StudentReg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 20));
        StudentReg.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));

        jLabel15.setText("Student Number:");
        StudentReg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, 20));

        jLabel16.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel16.setText("STUDENT ");
        StudentReg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, 30));

        jLabel17.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel17.setText("REGISTRATION");
        StudentReg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel22.setText("Class Name:");
        StudentReg.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));
        StudentReg.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 100, 20));

        buttonGroup3.add(jRadioButton3);
        jRadioButton3.setText("9");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        StudentReg.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setText("10");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        StudentReg.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        buttonGroup3.add(jRadioButton5);
        jRadioButton5.setText("11");
        StudentReg.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setText("12");
        StudentReg.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        jButton4.setText("ADD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        StudentReg.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, -1));
        StudentReg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 320, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentInformationSystem/background.png"))); // NOI18N
        jLabel6.setText("yrtyrtyrty");
        StudentReg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        Main.add(StudentReg);

        NoteEntry.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("SAVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        NoteEntry.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        NoteEntry.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 150, -1));

        jLabel9.setText("School Number:");
        NoteEntry.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 20));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        NoteEntry.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));
        NoteEntry.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 150, -1));

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        NoteEntry.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, 30));

        jLabel10.setText("Midterm:");
        NoteEntry.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 103, 50, 20));

        jLabel11.setText("Project:");
        NoteEntry.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 50, 20));
        NoteEntry.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel24.setText("Final:");
        NoteEntry.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 20));

        jLabel25.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel25.setText("NOTE ENTRY");
        NoteEntry.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));
        NoteEntry.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 250, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentInformationSystem/background.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        NoteEntry.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-54, -5, 560, 380));

        Main.add(NoteEntry);

        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settbuttActionPerformed
        // TODO add your handling code here:
         NoteEntry.setVisible(false);
        MainPage.setVisible(false);
        
        ListOfStudent.setVisible(false);
        Settings.setVisible(true);
        StudentReg.setVisible(false);
    }//GEN-LAST:event_settbuttActionPerformed

    private void exitbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttActionPerformed
         // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_exitbuttActionPerformed

    private void studentregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentregActionPerformed
        // TODO add your handling code here:
        NoteEntry.setVisible(false);
        MainPage.setVisible(false);
       
        ListOfStudent.setVisible(false);
        Settings.setVisible(false);
        StudentReg.setVisible(true);
    }//GEN-LAST:event_studentregActionPerformed

    private void ListOfStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListOfStudentsActionPerformed
        // TODO add your handling code here:
        NoteEntry.setVisible(false);
        MainPage.setVisible(false);
        
        ListOfStudent.setVisible(true);
        Settings.setVisible(false);
        StudentReg.setVisible(false);
    }//GEN-LAST:event_ListOfStudentsActionPerformed

    private void noteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteActionPerformed
        // TODO add your handling code here:
        NoteEntry.setVisible(true);
        MainPage.setVisible(false);
     
        ListOfStudent.setVisible(false);
        Settings.setVisible(false);
        StudentReg.setVisible(false);
    }//GEN-LAST:event_noteActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        try{
            
            Database database=new Database();
            int id=StudentsInformation.findId(Integer.parseInt(jTextField3.getText()));
            ArrayList<Information> arr=StudentsInformation.arr;
            Information information=new Information(arr.get(id).getId(),arr.get(id).getClassname(),arr.get(id).getGender(),arr.get(id).getnameSurname(),Double.parseDouble(jTextField7.getText()),Double.parseDouble(jTextField9.getText()),Double.parseDouble(jTextField8.getText()));            
            database.changeGrader(information);
            jLabel29.setText("the student's grades were entered");
        }catch(Exception e){
            System.out.println(e);
            jLabel29.setText("the student's grades were not entered");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            if(!jTextField2.equals("")&&!jTextField4.equals("")){
            Information people;
            Database database=new Database();
        
        if(jRadioButton3.isSelected()){
            if (jRadioButton1.isSelected()){
                 people = new Information(Integer.parseInt(jTextField4.getText()),9,"M",jTextField2.getText(),0,0,0);
                 database.addStudent(people);
                 jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }
            else{
                 people = new Information(Integer.parseInt(jTextField4.getText()),9,"F",jTextField2.getText(),0,0,0);
                 database.addStudent(people);
                 jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }
        }
        if (jRadioButton4.isSelected()){
            if (jRadioButton1.isSelected()){
                 people = new Information(Integer.parseInt(jTextField4.getText()),10,"M",jTextField2.getText(),0,0,0);
                database.addStudent(people);
                jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }
            else{
                 people = new Information(Integer.parseInt(jTextField4.getText()),10,"F",jTextField2.getText(),0,0,0);
                 database.addStudent(people);
                 jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }

        }
        if (jRadioButton5.isSelected()){
            if (jRadioButton1.isSelected()){
                 people = new Information(Integer.parseInt(jTextField4.getText()),11,"M",jTextField2.getText(),0,0,0);
                 database.addStudent(people);
                 jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }
            else{
                 people = new Information(Integer.parseInt(jTextField4.getText()),11,"F",jTextField2.getText(),0,0,0);
                 database.addStudent(people);
                 jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }
        }
        if (jRadioButton6.isSelected()){
            if (jRadioButton1.isSelected()){
                 people = new Information(Integer.parseInt(jTextField4.getText()),12,"M",jTextField2.getText(),0,0,0);
                 database.addStudent(people);
                 jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }
            else{
                 people = new Information(Integer.parseInt(jTextField4.getText()),12,"F",jTextField2.getText(),0,0,0);
                 database.addStudent(people);
                 jLabel2.setText(jTextField2.getText()+" "+"has been added to the list");
            }
        }
        
         }
        }catch(Exception e){
            jLabel2.setText("you entered the data type incorrectly");
        
        
        
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Database database=new Database();
        database.changePasswordandUserId(jTextField5.getText(), jTextField6.getText());
        jLabel27.setText("Successful!");
            
         
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton7MouseClicked
        // TODO add your handling code here:
        createTable(9);
    }//GEN-LAST:event_jRadioButton7MouseClicked

    private void jRadioButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton10MouseClicked
        // TODO add your handling code here:
        createTable(10);
    }//GEN-LAST:event_jRadioButton10MouseClicked

    private void jRadioButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton9MouseClicked
        // TODO add your handling code here:
        createTable(11);
    }//GEN-LAST:event_jRadioButton9MouseClicked

    private void jRadioButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton8MouseClicked
        // TODO add your handling code here:
        createTable(12);
    }//GEN-LAST:event_jRadioButton8MouseClicked

    private void jRadioButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton11MouseClicked
        // TODO add your handling code here:
        createTable(13);
    }//GEN-LAST:event_jRadioButton11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentsInformation.arr.clear();
        Database database=new Database();
        database.deleteAll();
        jLabel28.setText("All data has been deleted");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListOfStudent;
    private javax.swing.JButton ListOfStudents;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel MainPage;
    private javax.swing.JPanel NoteEntry;
    private javax.swing.JPanel Settings;
    private javax.swing.JPanel StudentReg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton exitbutt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton note;
    private javax.swing.JButton settbutt;
    private javax.swing.JButton studentreg;
    // End of variables declaration//GEN-END:variables

    private void createTable(int i) {
        DefaultTableModel model1=(DefaultTableModel) jTable1.getModel();
        model1.setRowCount(0);
        ArrayList<Information> arr=StudentsInformation.arr;
        for(int j=0;j<arr.size();j++){
            if(arr.get(j).getClassname()==i){
                model1.addRow(new Object[]{arr.get(j).getId(),arr.get(j).getnameSurname(),arr.get(j).getGender(),arr.get(j).getMidtermExams(),arr.get(j).getFinalExam(),arr.get(j).getProject()});
            }
            if(i==13){
                 model1.addRow(new Object[]{arr.get(j).getId(),arr.get(j).getnameSurname(),arr.get(j).getGender(),arr.get(j).getMidtermExams(),arr.get(j).getFinalExam(),arr.get(j).getProject()});
            }
        }
    }

   
}
